  name: Create builds

  on:
    workflow_dispatch:
      inputs:
        isMajorUpdate:
          description: 'Versioning should be increased by a major version'
          required: true
          type: boolean

  jobs:
    buildWin:
      runs-on: windows-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20.5.1'

        - name: Install dependencies
          run: yarn install

        - name: Build the project
          shell: yarn run dist-win

        - name: check for file
          run: cd dist && ls

        - name: check for file
          run: cd dist/upload && ls

        - name: Upload file as artifact
          uses: actions/upload-artifact@v4
          with:
            name: windows-build
            path: dist/upload/Dr.Json-windows.zip
            if-no-files-found: error
            retention-days: 1
            overwrite: true
            include-hidden-files: true
            compression-level: 0

    buildMac:
      needs: [buildWin]
      runs-on: macos-14

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20.5.1'

        - name: Install Yarn
          run: npm install --global yarn

        - name: Install dependencies
          run: yarn install

        - name: Build the project
          run: yarn run dist

        - name: check for file
          run: cd dist/upload && ls

        - name: Upload file as artifact
          uses: actions/upload-artifact@v4
          with:
            name: mac-build
            path: dist/upload/Dr.Json-arm64.zip
            if-no-files-found: error
            retention-days: 1
            overwrite: true
            include-hidden-files: true
            compression-level: 0

    retrieveArtifacts:
      needs: [buildWin, buildMac]
      runs-on: macos-14

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Download win file artifact
          uses: actions/download-artifact@v4
          with:
            name: windows-build
            path: dist/upload/Dr.Json-windows.zip

        - name: Download mac file artifact
          uses: actions/download-artifact@v4
          with:
            name: mac-build
            path: dist/upload/Dr.Json-arm64.zip

        - run: cd dist/upload && ls